/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle;

import java.lang.reflect.Array;

import com.google.common.base.Strings;
import com.google.common.primitives.Booleans;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public static void registrarUsuario(){
        String nom = "Roberto";

    }

    public static void eliminarUsuario(){
        String nom = "Robert";
        nom.equals("Robert");
        nom.replaceFirst("Robert", null);
    }

    public static void añadirLibro() {
        String libro = "Cuento";
        String libro2 = "Marciano";
        String autor = "Pizzasso";
        String[] lista = {"Marica", libro, libro2};
        if () {

        }
    }

    public static void eliminarLibro(){
        String libro = "cuento";
        libro.equals(libro);
        libro.replace("cuento", null);
    }

    public static void listarLibros(){
        String libro;
        String lista[];
    }

    public static void marcarComoLeido(){
        String usuario = "Paco"; 
        String libro = "cuento";
        boolean leido = false;
        if (libro != null) {
            leido = true;
        }
    }

    public static void verLibrosLeidos(){
        String libro = "Marciano";
        String[] lista = {"Marica", libro};
        boolean leido = false;
        if (leido == true) {

        }
    }
}
