/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle;

import org.junit.jupiter.api.Test;


class AppTest {
    @Test
    void testAñadirLibro() {
        
    }

    @Test
    void testEliminarLibro() {
        
    }

    @Test
    void testEliminarUsuario() {
        
    }

    @Test
    void testListarLibros() {
        
    }

    @Test
    void testMarcarComoLeido() {
        
    }

    @Test
    void testRegistrarUsuario() {
        
    }

    @Test
    void testVerLibrosLeidos() {
        
    }
}
