/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import gradle.App;

class AppTest {

    @Test void registrarUsuario() {
        App classUnderTest = new App();
        registrarUsuario();
    }

    @Test void eliminarUsuario() {
        App classUnderTest = new App();
        eliminarUsuario();
    }

    @Test void añadirLibro() {
        App classUnderTest = new App();
        añadirLibro();
    }

    @Test void eliminarLibro() {
        App classUnderTest = new App();
        eliminarLibro();
    }

    @Test void listarLibros() {
        App classUnderTest = new App();
    }
}
