/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void registrarUsuario() {
        App classUnderTest = new App();
        registrarUsuario(nom, correo);
    }

    @Test void eliminarUsuario() {
        App classUnderTest = new App();
        eliminarUsuario(equals(nom));
    }

    @Test void añadirLibro() {
        App classUnderTest = new App();
        añadirLibro(titol, autor);
    }

    @Test void eliminarLibro() {
        App classUnderTest = new App();
        eliminarLibro(equals(titol));
    }

    @Test void listarLibros() {
        App classUnderTest = new App();
        toString(listarLibros());
    }
}
